/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab_project;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author shawa
 */
public class homePageFromAdmin extends javax.swing.JFrame {
    private DefaultListModel<String> postListModel;
    /**
     * Creates new form homePageFromAdmin
     */
    public homePageFromAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        postListModel = new DefaultListModel<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hp_txt_post = new javax.swing.JTextField();
        hp_bAddPost = new javax.swing.JButton();
        darkMode = new javax.swing.JToggleButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hp_txt_area_posts = new javax.swing.JTextArea();
        hp_bAddFriend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelclose = new javax.swing.JLabel();
        jLabelmin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hp_bAddFriend1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(226, 241, 242));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        hp_txt_post.setBackground(new java.awt.Color(246, 250, 247));
        hp_txt_post.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hp_txt_postFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hp_txt_postFocusLost(evt);
            }
        });

        hp_bAddPost.setBackground(new java.awt.Color(246, 250, 247));
        hp_bAddPost.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        hp_bAddPost.setText("+");
        hp_bAddPost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hp_bAddPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hp_bAddPostActionPerformed(evt);
            }
        });

        darkMode.setBackground(new java.awt.Color(246, 250, 247));
        darkMode.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\dark-mode.png")); // NOI18N
        darkMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        darkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkModeActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(246, 250, 247));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\Help.png")); // NOI18N
        jButton6.setToolTipText("Help");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        hp_txt_area_posts.setEditable(false);
        hp_txt_area_posts.setBackground(new java.awt.Color(226, 241, 242));
        hp_txt_area_posts.setColumns(20);
        hp_txt_area_posts.setRows(5);
        jScrollPane1.setViewportView(hp_txt_area_posts);

        hp_bAddFriend.setBackground(new java.awt.Color(246, 250, 247));
        hp_bAddFriend.setText("Add friends");
        hp_bAddFriend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hp_bAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hp_bAddFriendActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("All Copy Rights reserved ©");

        jPanel2.setBackground(new java.awt.Color(3, 73, 86));
        jPanel2.setLayout(null);

        jLabelclose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelclose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelclose.setText("x");
        jLabelclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcloseMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelclose);
        jLabelclose.setBounds(770, 20, 20, 20);

        jLabelmin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmin.setText("-");
        jLabelmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelminMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelmin);
        jLabelmin.setBounds(740, 20, 20, 20);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Facelook");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 200, 42);

        hp_bAddFriend1.setBackground(new java.awt.Color(246, 250, 247));
        hp_bAddFriend1.setText("Return to admin page");
        hp_bAddFriend1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hp_bAddFriend1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hp_bAddFriend1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(hp_bAddFriend)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(darkMode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hp_bAddFriend1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(hp_txt_post, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(hp_bAddPost, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(hp_bAddFriend1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hp_txt_post, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hp_bAddPost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(darkMode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(hp_bAddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(319, 319, 319)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1);

        jMenu1.setText("Account");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\settings (1).png")); // NOI18N
        jMenu2.setText("Setting");

        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\question.png")); // NOI18N
        jMenuItem2.setText("Help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenu1.add(jMenu2);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("About US");

        jMenuItem4.setText("About us");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("contact Us");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hp_txt_postFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hp_txt_postFocusGained
        if (hp_txt_post.getText().equals("Whats on your minde?")) {
            hp_txt_post.setText("");
            hp_txt_post.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_hp_txt_postFocusGained

    private void hp_txt_postFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hp_txt_postFocusLost
        if (hp_txt_post.getText().toLowerCase().equals("email")
            || hp_txt_post.getText().toLowerCase().equals("")) {
            hp_txt_post.setText("Whats on your minde?");
            hp_txt_post.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_hp_txt_postFocusLost

    private void hp_bAddPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hp_bAddPostActionPerformed
        String postText = hp_txt_post.getText();
        if (!postText.trim().equals("")) {
            Post npost = new Post();
            npost.iduser = Social_Media_Helper.getCurrentId();
            npost.text = postText;

            if (!postText.isEmpty()) {
                if (Social_Media_Helper.addPost(npost)) {
                    hp_txt_post.setText("");
                    hp_txt_area_posts.setText("");
                    ArrayList<String> user_posts = Social_Media_Helper.getUserPosts(Social_Media_Helper.getCurrentId());

                    for (String post : user_posts) {
                        //                        hp_txt_area_posts.append(Social_Media_Helper.getCurrentUser().name + "\n");
                        hp_txt_area_posts.append(post + "\n\n");
                        //                        postListModel.addElement(post);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Error adding post.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {

        }
    }//GEN-LAST:event_hp_bAddPostActionPerformed

    private void darkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkModeActionPerformed
        if (darkMode.isSelected()) {
            jPanel1.setBackground(new Color(38,78,112));
            hp_txt_post.setBackground(new Color(38,78,112));
            hp_txt_area_posts.setBackground(new Color(38,78,112));
            jLabel4.setForeground(new Color(38,78,112));
            jLabelmin.setForeground(new Color(38,78,112));
            jLabelclose.setForeground(new Color(38,78,112));
            jPanel2.setBackground(new Color(250,105,0));
            hp_txt_post.setForeground(Color.white);
            hp_txt_area_posts.setForeground(Color.white);
            jLabel1.setForeground(Color.white);
        } else {
            homePageFromAdmin homePage = new homePageFromAdmin();
            homePage.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_darkModeActionPerformed

    private void hp_bAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hp_bAddFriendActionPerformed
        AddFriendFromAdmin addFriend = new AddFriendFromAdmin();
        addFriend.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hp_bAddFriendActionPerformed

    private void jLabelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelcloseMouseClicked

    private void jLabelminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelminMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelminMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        homePageFromAdmin homePage = new homePageFromAdmin();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void hp_bAddFriend1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hp_bAddFriend1ActionPerformed
        AdminPage adminfrm = new AdminPage();
        adminfrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hp_bAddFriend1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        HelpFromAdmin help = new HelpFromAdmin();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        HelpFromAdmin help = new HelpFromAdmin();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePageFromAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePageFromAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePageFromAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePageFromAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePageFromAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton darkMode;
    private javax.swing.JButton hp_bAddFriend;
    private javax.swing.JButton hp_bAddFriend1;
    private javax.swing.JButton hp_bAddPost;
    private javax.swing.JTextArea hp_txt_area_posts;
    public static javax.swing.JTextField hp_txt_post;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLabelmin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
