/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab_project;

    import java.util.ArrayList;
    import javax.swing.JFrame;
    import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shawa
 */
public class profil extends javax.swing.JFrame {
    int userId;
//    private DefaultListModel<String> postListModel;
    public DefaultTableModel tbl_table_model;
//    public DefaultTableModel tb2_table_model;

    /**
     * Creates new form profil
     */
    public profil(int userId) {
        initComponents();
        this.userId = userId;
        this.setLocationRelativeTo(null);
        tbl_table_model = new DefaultTableModel();
//        tb2_table_model = new DefaultTableModel();
        tbl_table_model.setColumnIdentifiers(new Object[]{"name", "lastname", "email", "gender", "nationality"});
//        tb2_table_model.setColumnIdentifiers(new Object[]{"Posts"});
        profile_user_friends.setModel(tbl_table_model);
//        profile_user_posts.setModel(tb2_table_model);
        profile_name.setText(Social_Media_Helper.getCurrentUserFromId(this.userId).name);
        profile_lastname.setText(Social_Media_Helper.getCurrentUserFromId(this.userId).lastname);
//        postListModel = new DefaultListModel<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        profile_name = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelclose = new javax.swing.JLabel();
        jLabelmin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        profile_user_friends = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        profile_lastname = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        profile_user_posts = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        editInfo = new javax.swing.JButton();

        jLabel7.setBackground(new java.awt.Color(102, 0, 0));
        jLabel7.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(226, 241, 242));
        jPanel1.setForeground(new java.awt.Color(226, 241, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(226, 241, 242));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\user (1).png")); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 104, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 283, 54, 27));

        jButton1.setText("Return to Home Page");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 545, -1, -1));

        profile_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profile_name.setText("user name ");
        jPanel1.add(profile_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 286, -1, -1));

        jButton3.setText("Show Friends");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 148, -1, -1));

        jButton4.setText("Delete");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 181, 104, -1));

        jPanel2.setBackground(new java.awt.Color(3, 73, 86));
        jPanel2.setLayout(null);

        jLabelclose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelclose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelclose.setText("x");
        jLabelclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcloseMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelclose);
        jLabelclose.setBounds(760, 20, 20, 20);

        jLabelmin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmin.setText("-");
        jLabelmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelminMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelmin);
        jLabelmin.setBounds(730, 20, 20, 20);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Facelook");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 200, 42);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 70));

        jPanel6.setLayout(null);

        profile_user_friends.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Last Name", "Email", "Gender", "Nationality"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(profile_user_friends);
        if (profile_user_friends.getColumnModel().getColumnCount() > 0) {
            profile_user_friends.getColumnModel().getColumn(0).setResizable(false);
            profile_user_friends.getColumnModel().getColumn(1).setResizable(false);
            profile_user_friends.getColumnModel().getColumn(1).setHeaderValue("Last Name");
            profile_user_friends.getColumnModel().getColumn(2).setResizable(false);
            profile_user_friends.getColumnModel().getColumn(2).setHeaderValue("Email");
            profile_user_friends.getColumnModel().getColumn(3).setResizable(false);
            profile_user_friends.getColumnModel().getColumn(3).setHeaderValue("Gender");
            profile_user_friends.getColumnModel().getColumn(4).setResizable(false);
            profile_user_friends.getColumnModel().getColumn(4).setHeaderValue("Nationality");
        }

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 320, 190);

        jPanel5.setBackground(new java.awt.Color(242, 103, 34));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Friends List");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(jPanel5);
        jPanel5.setBounds(0, 0, 320, 41);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 80, 319, 230));

        profile_lastname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profile_lastname.setText("user surname ");
        jPanel1.add(profile_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 286, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 328, 429, 10));

        jButton5.setText("Edit Post");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 427, 104, -1));

        jButton6.setText("Show Posts");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 394, 104, -1));

        jButton7.setText("Delete");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 460, 104, -1));

        jPanel7.setLayout(null);

        profile_user_posts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Post ID", "Post"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        profile_user_posts.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(profile_user_posts);
        if (profile_user_posts.getColumnModel().getColumnCount() > 0) {
            profile_user_posts.getColumnModel().getColumn(0).setResizable(false);
            profile_user_posts.getColumnModel().getColumn(0).setPreferredWidth(10);
            profile_user_posts.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel7.add(jScrollPane3);
        jScrollPane3.setBounds(0, 40, 320, 190);

        jPanel8.setBackground(new java.awt.Color(242, 103, 34));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Post List");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 0, 320, 41);

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 364, 319, 230));

        editInfo.setText("Edit Personal info");
        editInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInfoActionPerformed(evt);
            }
        });
        jPanel1.add(editInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 364, 139, 36));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        user_home_page_frame homePage = new user_home_page_frame();
        homePage.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed
    private void showUserFriendsDetails() {
        tbl_table_model.setRowCount(0);
        int currentUserId = this.userId;
        ArrayList<Integer> friendIds = Social_Media_Helper.getCurrentUserFriendsIds(currentUserId);
        for (int friendId : friendIds) {
            User friend = Social_Media_Helper.getCurrentUserFromId(friendId);
            if (friend != null) {
                tbl_table_model.addRow(new Object[]{friend.name, friend.lastname, friend.email, friend.gender, friend.nationality});
            }
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        showUserFriendsDetails();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int selectedRow = profile_user_friends.getSelectedRow();
        if (selectedRow != -1) {
            String email = (String) tbl_table_model.getValueAt(selectedRow, 2);
            User selectedUser;
            selectedUser = Social_Media_Helper.getCurrentUserFromEmail(email);
            int friendId = selectedUser.iduser;
            if (Social_Media_Helper.deleteFriend(this.userId, friendId)) {
                JOptionPane.showMessageDialog(rootPane, "Friend deleted successfully");
                tbl_table_model.setRowCount(0);
                showUserFriendsDetails();

            } else {
                JOptionPane.showMessageDialog(rootPane, "Failed to delete friend.");
            }
        } else {

            JOptionPane.showMessageDialog(rootPane, "No row selected.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelcloseMouseClicked

    private void jLabelminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelminMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelminMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        user_home_page_frame homePage = new user_home_page_frame();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int selectedRow = profile_user_posts.getSelectedRow();
        if (selectedRow != -1) {
            int postId = (int) profile_user_posts.getModel().getValueAt(selectedRow, 0);
            String post = (String) profile_user_posts.getModel().getValueAt(selectedRow, 1);
            String editPost = JOptionPane.showInputDialog(rootPane,"Enter the new post you want", post);
            
            if (Social_Media_Helper.editPost(postId, editPost)) {
                profile_user_posts.setModel(new DefaultTableModel());
                DefaultTableModel user_posts = Social_Media_Helper.getCurrentUserPosts(this.userId);
                profile_user_posts.setModel(user_posts);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Failed to delete post", "warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No row selected.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel user_posts = Social_Media_Helper.getCurrentUserPosts(this.userId);
        profile_user_posts.setModel(user_posts);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int selectedRow = profile_user_posts.getSelectedRow();
        if (selectedRow != -1) {
            int postId = (int) profile_user_posts.getModel().getValueAt(selectedRow, 0);
            if (Social_Media_Helper.deletePost(postId)) {
                profile_user_posts.setModel(new DefaultTableModel());
                DefaultTableModel user_posts = Social_Media_Helper.getCurrentUserPosts(this.userId);
                profile_user_posts.setModel(user_posts);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Failed to delete post", "warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No row selected.");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void editInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInfoActionPerformed
        User user;
        user = Social_Media_Helper.getCurrentUserFromId(this.userId);
        String newName = JOptionPane.showInputDialog(this, "Enter updated name:", user.name);
        String newLastName = JOptionPane.showInputDialog(this, "Enter updated sure name:", user.lastname);
        String newPhoneNumber = JOptionPane.showInputDialog(this, "Enter updated name:", user.phonenumber);
        String newPassword = JOptionPane.showInputDialog(this, "Enter updated name:", user.password);
        if(Social_Media_Helper.editUserInfo(this.userId, newName, newLastName, newPhoneNumber, newPassword)){
            JOptionPane.showMessageDialog(rootPane,"Your Info has bee updated succsesfully","Info", JOptionPane.INFORMATION_MESSAGE);
            profile_name.setText(newName);
            profile_lastname.setText(newLastName);
        }else {
            JOptionPane.showMessageDialog(rootPane,"Error in updating","error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profil(-1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLabelmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel profile_lastname;
    public javax.swing.JLabel profile_name;
    private javax.swing.JTable profile_user_friends;
    private javax.swing.JTable profile_user_posts;
    // End of variables declaration//GEN-END:variables
}
