/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab_project;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author shawa
 */
public class signintest extends javax.swing.JFrame {

    /**
     * Creates new form signintest
     */
    public signintest() {
        initComponents();
        this.setLocationRelativeTo(null);
        signIn_txt_email.setText("email");
        signIn_txt_email.setForeground(new Color(153, 153, 153));
        signIn_txt_password.setText("password");
        signIn_txt_password.setForeground(new Color(153, 153, 153));

//        ImageIcon imageIcon = new ImageIcon("file:/C:/Users/shawa/OneDrive/Documents/NetBeansProjects/Lab_Project/images/user.png"); // load the image to a imageIcon
//        Image image = imageIcon.getImage(); // transform it 
//        Image newimg = image.getScaledInstance(39, 39, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
//        imageIcon = new ImageIcon(newimg);
//        q.setIcon(imageIcon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelclose = new javax.swing.JLabel();
        jLabelmin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        signIn_txt_email = new javax.swing.JTextField();
        jCheckBoxShowPass = new javax.swing.JCheckBox();
        signIn_txt_password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelCreateAccount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(440, 380));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(3, 73, 86));
        jPanel1.setLayout(null);

        jLabelclose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelclose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelclose.setText("x");
        jLabelclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelclose);
        jLabelclose.setBounds(400, 20, 20, 20);

        jLabelmin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmin.setText("-");
        jLabelmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelminMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelmin);
        jLabelmin.setBounds(370, 20, 20, 20);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Facelook");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 10, 200, 42);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 70);

        jPanel2.setBackground(new java.awt.Color(226, 241, 242));
        jPanel2.setMinimumSize(new java.awt.Dimension(440, 370));
        jPanel2.setPreferredSize(new java.awt.Dimension(440, 370));

        signIn_txt_email.setBackground(new java.awt.Color(246, 250, 247));
        signIn_txt_email.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        signIn_txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signIn_txt_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signIn_txt_emailFocusLost(evt);
            }
        });
        signIn_txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signIn_txt_emailActionPerformed(evt);
            }
        });

        jCheckBoxShowPass.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jCheckBoxShowPass.setText("Show Password");
        jCheckBoxShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPassActionPerformed(evt);
            }
        });

        signIn_txt_password.setBackground(new java.awt.Color(246, 250, 247));
        signIn_txt_password.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        signIn_txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signIn_txt_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signIn_txt_passwordFocusLost(evt);
            }
        });
        signIn_txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signIn_txt_passwordActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(38, 166, 91));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(242, 103, 34));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelCreateAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCreateAccount.setText("New user? Click here to creat an account");
        jLabelCreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCreateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCreateAccountMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(236, 100, 75));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\user (5).png")); // NOI18N

        jLabel5.setBackground(new java.awt.Color(236, 100, 75));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\forgot.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabelCreateAccount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signIn_txt_email)
                    .addComponent(signIn_txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxShowPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signIn_txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCheckBoxShowPass)
                    .addComponent(signIn_txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelCreateAccount)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 440, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelminMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelminMouseClicked

    private void jLabelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelcloseMouseClicked

    private void jCheckBoxShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPassActionPerformed
        if (jCheckBoxShowPass.isSelected()) {
            signIn_txt_password.setEchoChar((char) 0);
        } else {
            signIn_txt_password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email = signIn_txt_email.getText();
        String password = signIn_txt_password.getText();
        User ruser = Social_Media_Helper.SignIn(email, password);
        if (ruser != null) {
            user_home_page_frame frmCustomer = new user_home_page_frame();
            frmCustomer.setVisible(true);
            this.dispose();
            user_home_page_frame.hp_txt_post.setText("Whats on your minde?");
            user_home_page_frame.hp_txt_post.setForeground(new Color(153, 153, 153));
        } else {
            JOptionPane.showMessageDialog(rootPane, "User can not be found...");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabelCreateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCreateAccountMouseClicked
        signUp_1 subf = new signUp_1();
        subf.setVisible(true);
        subf.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_jLabelCreateAccountMouseClicked

    private void signIn_txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signIn_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signIn_txt_passwordActionPerformed

    private void signIn_txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signIn_txt_emailFocusGained
        if (signIn_txt_email.getText().trim().toLowerCase().equals("email")) {
            signIn_txt_email.setText("");
            signIn_txt_email.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_signIn_txt_emailFocusGained

    private void signIn_txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signIn_txt_emailFocusLost
        if (signIn_txt_email.getText().trim().toLowerCase().equals("email")
                || signIn_txt_email.getText().trim().toLowerCase().equals("")) {
            signIn_txt_email.setText("email");
            signIn_txt_email.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_signIn_txt_emailFocusLost

    private void signIn_txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signIn_txt_passwordFocusGained
        String password = String.valueOf(signIn_txt_password.getPassword());
        if (password.trim().toLowerCase().equals("password")) {
            signIn_txt_password.setText("");
            signIn_txt_password.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_signIn_txt_passwordFocusGained

    private void signIn_txt_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signIn_txt_passwordFocusLost
        String password = String.valueOf(signIn_txt_password.getPassword());
        if (password.trim().toLowerCase().equals("password")
                || password.trim().toLowerCase().equals("")) {
            signIn_txt_password.setText("password");
            signIn_txt_password.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_signIn_txt_passwordFocusLost

    private void signIn_txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signIn_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signIn_txt_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signintest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signintest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signintest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signintest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signintest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxShowPass;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCreateAccount;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLabelmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField signIn_txt_email;
    public static javax.swing.JPasswordField signIn_txt_password;
    // End of variables declaration//GEN-END:variables
}
