/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab_project;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author shawa
 */
public class user_home_page_frame extends javax.swing.JFrame {

    private static DefaultListModel<String> postListModel;

    /**
     * Creates new form user_home_page_frame
     */
    public user_home_page_frame() {
        initComponents();
        this.setLocationRelativeTo(null);
//        postListModel = new DefaultListModel<>();
        ArrayList<String> user_posts = Social_Media_Helper.getUserPosts(Social_Media_Helper.getCurrentId());
        for (int i = user_posts.size() - 1; i >= 0; i--) {
            String post = user_posts.get(i);
            hp_txt_area_posts.append(post + "\n\n");
        }

    }

    public void showPopUp(MouseEvent e) {
        jPopupMenu1.show(this, e.getX(), e.getY());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Save = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        hp_txt_post = new javax.swing.JTextField();
        hp_bAddPost = new javax.swing.JButton();
        darkMode = new javax.swing.JToggleButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hp_txt_area_posts = new javax.swing.JTextArea();
        hp_bAddFriend = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelclose = new javax.swing.JLabel();
        jLabelmin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Save);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Exit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(226, 241, 242));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        hp_txt_post.setBackground(new java.awt.Color(246, 250, 247));
        hp_txt_post.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hp_txt_postFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hp_txt_postFocusLost(evt);
            }
        });

        hp_bAddPost.setBackground(new java.awt.Color(246, 250, 247));
        hp_bAddPost.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        hp_bAddPost.setText("+");
        hp_bAddPost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hp_bAddPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hp_bAddPostActionPerformed(evt);
            }
        });

        darkMode.setBackground(new java.awt.Color(246, 250, 247));
        darkMode.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\dark-mode.png")); // NOI18N
        darkMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        darkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkModeActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(246, 250, 247));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\logout.png")); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(246, 250, 247));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\Help.png")); // NOI18N
        jButton6.setToolTipText("Help");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        hp_txt_area_posts.setEditable(false);
        hp_txt_area_posts.setBackground(new java.awt.Color(226, 241, 242));
        hp_txt_area_posts.setColumns(20);
        hp_txt_area_posts.setRows(5);
        jScrollPane1.setViewportView(hp_txt_area_posts);

        hp_bAddFriend.setBackground(new java.awt.Color(246, 250, 247));
        hp_bAddFriend.setText("Add friends");
        hp_bAddFriend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hp_bAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hp_bAddFriendActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(246, 250, 247));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\profile (1).png")); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("All Copy Rights reserved ©");

        jPanel2.setBackground(new java.awt.Color(3, 73, 86));
        jPanel2.setLayout(null);

        jLabelclose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelclose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelclose.setText("x");
        jLabelclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcloseMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelclose);
        jLabelclose.setBounds(770, 20, 20, 20);

        jLabelmin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmin.setText("-");
        jLabelmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelminMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelmin);
        jLabelmin.setBounds(740, 20, 20, 20);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Facelook");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 200, 42);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(hp_txt_post, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(hp_bAddPost, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hp_bAddFriend)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(darkMode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hp_txt_post, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hp_bAddPost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(312, 312, 312)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(darkMode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hp_bAddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);

        jMenu1.setText("Account");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\profile.png")); // NOI18N
        jMenuItem1.setText("Profile");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\settings (1).png")); // NOI18N
        jMenu2.setText("Setting");

        jCheckBoxMenuItem1.setText("Dark Mode");
        jCheckBoxMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\dark-mode (1).png")); // NOI18N
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\question.png")); // NOI18N
        jMenuItem2.setText("Help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenu1.add(jMenu2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_QUOTE, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\shawa\\Downloads\\logout (1).png")); // NOI18N
        jMenuItem3.setText("Log out");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("About US");

        jMenuItem4.setText("About us");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void darkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkModeActionPerformed
        if (darkMode.isSelected()) {

            jPanel1.setBackground(new Color(38, 78, 112));
            hp_txt_post.setBackground(new Color(38, 78, 112));
            hp_txt_area_posts.setBackground(new Color(38, 78, 112));
            jLabel4.setForeground(new Color(38, 78, 112));
            jLabelmin.setForeground(new Color(38, 78, 112));
            jLabelclose.setForeground(new Color(38, 78, 112));
            jPanel2.setBackground(new Color(250, 105, 0));
            hp_txt_post.setForeground(Color.white);
            hp_txt_area_posts.setForeground(Color.white);
            jLabel1.setForeground(Color.white);
        } else {

            user_home_page_frame homePage = new user_home_page_frame();
            homePage.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_darkModeActionPerformed

    private void hp_bAddPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hp_bAddPostActionPerformed
        String postText = hp_txt_post.getText();
        if (!postText.trim().equals("")) {
            Post npost = new Post();
            npost.iduser = Social_Media_Helper.getCurrentId();
            npost.text = postText;

            if (!postText.isEmpty()) {
                if (Social_Media_Helper.addPost(npost)) {
                    hp_txt_post.setText("");
                    hp_txt_area_posts.setText("");
                    ArrayList<String> user_posts = Social_Media_Helper.getUserPosts(Social_Media_Helper.getCurrentId());
                    for (int i = user_posts.size() - 1; i >= 0; i--) {
                        String post = user_posts.get(i);
                        hp_txt_area_posts.append(post + "\n\n");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Error adding post.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {

        }
    }//GEN-LAST:event_hp_bAddPostActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        profil pfrm = new profil(Social_Media_Helper.getCurrentId());
        pfrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void hp_bAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hp_bAddFriendActionPerformed
        AddFriend addFriend = new AddFriend();
        addFriend.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_hp_bAddFriendActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        profil pfrm = new profil(Social_Media_Helper.getCurrentId());
        pfrm.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int choice2 = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to sign out", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choice2 == JOptionPane.YES_OPTION) {
            signintest subf = new signintest();
            subf.setVisible(true);
            subf.setLocationRelativeTo(null);
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void hp_txt_postFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hp_txt_postFocusGained
        if (hp_txt_post.getText().equals("Whats on your minde?")) {
            hp_txt_post.setText("");
            hp_txt_post.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_hp_txt_postFocusGained

    private void hp_txt_postFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hp_txt_postFocusLost
        if (hp_txt_post.getText().toLowerCase().equals("email")
                || hp_txt_post.getText().toLowerCase().equals("")) {
            hp_txt_post.setText("Whats on your minde?");
            hp_txt_post.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_hp_txt_postFocusLost

    private void jLabelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelcloseMouseClicked

    private void jLabelminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelminMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelminMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        user_home_page_frame homePage = new user_home_page_frame();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int choice2 = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to sign out", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choice2 == JOptionPane.YES_OPTION) {
            signintest subf = new signintest();
            subf.setVisible(true);
            subf.setLocationRelativeTo(null);
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Help help = new Help();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Help help = new Help();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Help help = new Help();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Saved successfully");
    }//GEN-LAST:event_SaveActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        if (evt.isPopupTrigger()) {
            showPopUp(evt);
        }
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        if (evt.isPopupTrigger()) {
            showPopUp(evt);
        }
    }//GEN-LAST:event_jPanel1MouseReleased

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        int choose = JOptionPane.showConfirmDialog(rootPane, "Are You sure you want to close the program?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (choose == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        if(jCheckBoxMenuItem1.isSelected()){
            jPanel1.setBackground(new Color(38, 78, 112));
            hp_txt_post.setBackground(new Color(38, 78, 112));
            hp_txt_area_posts.setBackground(new Color(38, 78, 112));
            jLabel4.setForeground(new Color(38, 78, 112));
            jLabelmin.setForeground(new Color(38, 78, 112));
            jLabelclose.setForeground(new Color(38, 78, 112));
            jPanel2.setBackground(new Color(250, 105, 0));
            hp_txt_post.setForeground(Color.white);
            hp_txt_area_posts.setForeground(Color.white);
            jLabel1.setForeground(Color.white);
        }else{
            user_home_page_frame homePage = new user_home_page_frame();
            homePage.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_home_page_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_home_page_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_home_page_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_home_page_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_home_page_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem Save;
    private javax.swing.JToggleButton darkMode;
    private javax.swing.JButton hp_bAddFriend;
    private javax.swing.JButton hp_bAddPost;
    private javax.swing.JTextArea hp_txt_area_posts;
    public static javax.swing.JTextField hp_txt_post;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLabelmin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
